//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xadrez.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TextoDasCasasColorido {
            get {
                return ((bool)(this["TextoDasCasasColorido"]));
            }
            set {
                this["TextoDasCasasColorido"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ColocarImagensNasCasas {
            get {
                return ((bool)(this["ColocarImagensNasCasas"]));
            }
            set {
                this["ColocarImagensNasCasas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoConcluirJogadaOn {
            get {
                return ((bool)(this["AutoConcluirJogadaOn"]));
            }
            set {
                this["AutoConcluirJogadaOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MostrarPopupDasCasas {
            get {
                return ((bool)(this["MostrarPopupDasCasas"]));
            }
            set {
                this["MostrarPopupDasCasas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VerInfoDeDebug {
            get {
                return ((bool)(this["VerInfoDeDebug"]));
            }
            set {
                this["VerInfoDeDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TestarTabuleiroDebug {
            get {
                return ((bool)(this["TestarTabuleiroDebug"]));
            }
            set {
                this["TestarTabuleiroDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InverterTabuleiro {
            get {
                return ((bool)(this["InverterTabuleiro"]));
            }
            set {
                this["InverterTabuleiro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte IdDaPessaQueOPeaoVaiVirar {
            get {
                return ((byte)(this["IdDaPessaQueOPeaoVaiVirar"]));
            }
            set {
                this["IdDaPessaQueOPeaoVaiVirar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HostIP {
            get {
                return ((string)(this["HostIP"]));
            }
            set {
                this["HostIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClientIP {
            get {
                return ((string)(this["ClientIP"]));
            }
            set {
                this["ClientIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SeEnviaMovimentosDeJogada {
            get {
                return ((bool)(this["SeEnviaMovimentosDeJogada"]));
            }
            set {
                this["SeEnviaMovimentosDeJogada"] = value;
            }
        }
    }
}
